// copy this function in devtools > console and call it 
function simulateInput() {
    const countries = [
        'iceland',
        'canada',
        'united states',
        'usa',
        'mexico',
        'guatemala',
        'belize',
        'honduras',
        'el salvador',
        'nicaragua',
        'costa rica',
        'panama',
        'colombia',
        'venezuela',
        'guyana',
        'suriname',
        'ecuador',
        'peru',
        'bolivia',
        'paraguay',
        'uruguay',
        'brazil',
        'chile',
        'argentina',
        'uk',
        'united kingdom',
        'britain',
        'ireland',
        'portugal',
        'spain',
        'france',
        'andorra',
        'monaco',
        'italy',
        'vatican',
        'san marino',
        'belgium',
        'netherlands',
        'the netherlands',
        'luxembourg',
        'switzerland',
        'germany',
        'denmark',
        'sweden',
        'norway',
        'finland',
        'estonia',
        'latvia',
        'lithuania',
        'poland',
        'belarus',
        'ukraine',
        'moldova',
        'romania',
        'czechia',
        'czech republic',
        'slovakia',
        'liechtenstein',
        'austria',
        'hungary',
        'slovenia',
        'croatia',
        'bosnia and herzegovina',
        'montenegro',
        'serbia',
        'kosovo',
        'albania',
        'macedonia',
        'north macedonia',
        'bulgaria',
        'greece',
        'turkey',
        'turkiye',
        'türkiye',
        'cyprus',
        'malta',
        'georgia',
        'armenia',
        'azerbaijan',
        'syria',
        'iraq',
        'kuwait',
        'lebanon',
        'israel',
        'palestine',
        'jordan',
        'saudi arabia',
        'uae',
        'united arab emirates',
        'oman',
        'yemen',
        'qatar',
        'bahrain',
        'afghanistan',
        'turkmenistan',
        'uzbekistan',
        'tajikistan',
        'kyrgyzstan',
        'kazakhstan',
        'russia',
        'japan',
        'south korea',
        'north korea',
        'mongolia',
        'china',
        'taiwan',
        'philippines',
        'pakistan',
        'india',
        'nepal',
        'bhutan',
        'bangladesh',
        'sri lanka',
        'myanmar',
        'burma',
        'thailand',
        'laos',
        'cambodia',
        'vietnam',
        'malaysia',
        'singapore',
        'indonesia',
        'east timor',
        'timor leste',
        'brunei',
        'papua new guinea',
        'australia',
        'new zealand',
        'fiji',
        'tonga',
        'tuvalu',
        'samoa',
        'kiribati',
        'micronesia',
        'palau',
        'nauru',
        'vanuatu',
        'solomon islands',
        'marshall islands',
        'maldives',
        'seychelles',
        'madagascar',
        'mauritius',
        'comoros',
        'eswatini',
        'lesotho',
        'south africa',
        'namibia',
        'angola',
        'botswana',
        'zimbabwe',
        'zambia',
        'mozambique',
        'malawi',
        'tanzania',
        'kenya',
        'burundi',
        'rwanda',
        'uganda',
        'congo',
        'drc',
        'democratic republic of congo',
        'democratic republic of the congo',
        'congo republic',
        'rep congo',
        'republic of congo',
        'republic of the congo',
        'gabon',
        'equatorial guinea',
        'cameroon',
        'central african republic',
        'car',
        'south sudan',
        'ethiopia',
        'somalia',
        'djibouti',
        'eritrea',
        'sudan',
        'egypt',
        'chad',
        'libya',
        'tunisia',
        'algeria',
        'niger',
        'nigeria',
        'benin',
        'togo',
        'ghana',
        'burkina faso',
        'ivory coast',
        'cote divoire',
        'liberia',
        'sierra leone',
        'guinea',
        'guinea bissau',
        'guinea-bissau',
        'senegal',
        'gambia',
        'the gambia',
        'mali',
        'mauritania',
        'morocco',
        'cabo verde',
        'cape verde',
        'sao tome and principe',
        'são tomé and príncipe',
        'cuba',
        'jamaica',
        'dominica',
        'trinidad and tobago',
        'st vincent',
        'st lucia',
        'haiti',
        'st kitts and nevis',
        'grenada',
        'barbados',
        'dominican republic',
        'bahamas',
        'antigua and barbuda',
        'iran',
    ];
    const myInput = document.getElementsByTagName('input')[0];

    function typeText(text, index) {
        if (index < text.length) {
            myInput.value += text[index];
            myInput.dispatchEvent(new Event('input', { bubbles: true }));
            index++;
            setTimeout(() => typeText(text, index), 50); // Adjust the delay (in milliseconds) as needed
        }
    }

    let countryIndex = 0;

    function simulateInputForNextCountry() {
        if (countryIndex < countries.length) {
            const currentCountry = countries[countryIndex];
            myInput.value = ''; // Clear input before typing new text
            typeText(currentCountry, 0);
            countryIndex++;
            console.log(`${countryIndex}: ${currentCountry}`);
            setTimeout(simulateInputForNextCountry, currentCountry.length * 50 + 300); // Adjust the delay as needed
        }
    }

    // Start the simulation
    simulateInputForNextCountry();
}
